In [4]:
import numpy as np
import pandas as pd

# Lab | Data Aggregation and Filtering

In this challenge, we will continue to work with customer data from an insurance company. We will use the dataset called marketing_customer_analysis.csv, which can be found at the following link:

https://raw.githubusercontent.com/data-bootcamp-v4/data/main/marketing_customer_analysis.csv

This dataset contains information such as customer demographics, policy details, vehicle information, and the customer's response to the last marketing campaign. Our goal is to explore and analyze this data by first performing data cleaning, formatting, and structuring.

In [5]:
url = "https://raw.githubusercontent.com/data-bootcamp-v4/data/main/marketing_customer_analysis.csv"
df = pd.read_csv(url)

In [6]:
df.columns = (
    df.columns
    .str.strip()
    .str.lower()
    .str.replace(" ", "_")
)

In [7]:
df.columns = (
    df.columns
    .str.strip()
    .str.lower()
    .str.replace(" ", "_")
)

df = df.rename(columns={
    "st": "state"
})
print(df.columns.tolist())

['unnamed:_0', 'customer', 'state', 'customer_lifetime_value', 'response', 'coverage', 'education', 'effective_to_date', 'employmentstatus', 'gender', 'income', 'location_code', 'marital_status', 'monthly_premium_auto', 'months_since_last_claim', 'months_since_policy_inception', 'number_of_open_complaints', 'number_of_policies', 'policy_type', 'policy', 'renew_offer_type', 'sales_channel', 'total_claim_amount', 'vehicle_class', 'vehicle_size', 'vehicle_type']

1. Create a new DataFrame that only includes customers who:
   - have a **low total_claim_amount** (e.g., below $1,000),
   - have a response "Yes" to the last marketing campaign.

In [8]:
df

,unnamed:_0,customer,state,customer_lifetime_value,response,coverage,education,effective_to_date,employmentstatus,gender,...,number_of_open_complaints,number_of_policies,policy_type,policy,renew_offer_type,sales_channel,total_claim_amount,vehicle_class,vehicle_size,vehicle_type
0,0,DK49336,Arizona,4809.216960,No,Basic,College,2/18/11,Employed,M,...,0.0,9,Corporate Auto,Corporate L3,Offer3,Agent,292.800000,Four-Door Car,Medsize,NaN
1,1,KX64629,California,2228.525238,No,Basic,College,1/18/11,Unemployed,F,...,0.0,1,Personal Auto,Personal L3,Offer4,Call Center,744.924331,Four-Door Car,Medsize,NaN
2,2,LZ68649,Washington,14947.917300,No,Basic,Bachelor,2/10/11,Employed,M,...,0.0,2,Personal Auto,Personal L3,Offer3,Call Center,480.000000,SUV,Medsize,A
3,3,XL78013,Oregon,22332.439460,Yes,Extended,College,1/11/11,Employed,M,...,0.0,2,Corporate Auto,Corporate L3,Offer2,Branch,484.013411,Four-Door Car,Medsize,A
4,4,QA50777,Oregon,9025.067525,No,Premium,Bachelor,1/17/11,Medical Leave,F,...,NaN,7,Personal Auto,Personal L2,Offer1,Branch,707.925645,Four-Door Car,Medsize,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10905,10905,FE99816,Nevada,15563.369440,No,Premium,Bachelor,1/19/11,Unemployed,F,...,NaN,7,Personal Auto,Personal L1,Offer3,Web,1214.400000,Luxury Car,Medsize,A
10906,10906,KX53892,Oregon,5259.444853,No,Basic,College,1/6/11,Employed,F,...,0.0,6,Personal Auto,Personal L3,Offer2,Branch,273.018929,Four-Door Car,Medsize,A
10907,10907,TL39050,Arizona,23893.304100,No,Extended,Bachelor,2/6/11,Employed,F,...,0.0,2,Corporate Auto,Corporate L3,Offer1,Web,381.306996,Luxury SUV,Medsize,NaN
10908,10908,WA60547,California,11971.977650,No,Premium,College,2/13/11,Employed,F,...,4.0,6,Personal Auto,Personal L1,Offer1,Branch,618.288849,SUV,Medsize,A
10909,10909,IV32877,NaN,6857.519928,NaN,Basic,Bachelor,1/8/11,Unemployed,M,...,0.0,3,Personal Auto,Personal L1,Offer4,Web,1021.719397,SUV,Medsize,NaN

In [9]:
filtered_df = df[(df["total_claim_amount"] < 1000) & (df["response"] == "Yes")].reset_index(drop=True)

In [10]:
filtered_df

,unnamed:_0,customer,state,customer_lifetime_value,response,coverage,education,effective_to_date,employmentstatus,gender,...,number_of_open_complaints,number_of_policies,policy_type,policy,renew_offer_type,sales_channel,total_claim_amount,vehicle_class,vehicle_size,vehicle_type
0,3,XL78013,Oregon,22332.439460,Yes,Extended,College,1/11/11,Employed,M,...,0.0,2,Corporate Auto,Corporate L3,Offer2,Branch,484.013411,Four-Door Car,Medsize,A
1,8,FM55990,California,5989.773931,Yes,Premium,College,1/19/11,Employed,M,...,0.0,1,Personal Auto,Personal L1,Offer2,Branch,739.200000,Sports Car,Medsize,NaN
2,15,CW49887,California,4626.801093,Yes,Basic,Master,1/16/11,Employed,F,...,0.0,1,Special Auto,Special L1,Offer2,Branch,547.200000,SUV,Medsize,NaN
3,19,NJ54277,California,3746.751625,Yes,Extended,College,2/26/11,Employed,F,...,1.0,1,Personal Auto,Personal L2,Offer2,Call Center,19.575683,Two-Door Car,Large,A
4,27,MQ68407,Oregon,4376.363592,Yes,Premium,Bachelor,2/28/11,Employed,F,...,0.0,1,Personal Auto,Personal L3,Offer2,Agent,60.036683,Four-Door Car,Medsize,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1394,10844,FM31768,Arizona,5979.724161,Yes,Extended,High School or Below,2/7/11,Employed,F,...,0.0,3,Personal Auto,Personal L1,Offer2,Agent,547.200000,Four-Door Car,Medsize,NaN
1395,10852,KZ80424,Washington,8382.478392,Yes,Basic,Bachelor,1/27/11,Employed,M,...,0.0,2,Personal Auto,Personal L2,Offer2,Call Center,791.878042,NaN,NaN,A
1396,10872,XT67997,California,5979.724161,Yes,Extended,High School or Below,2/7/11,Employed,F,...,0.0,3,Personal Auto,Personal L3,Offer2,Agent,547.200000,Four-Door Car,Medsize,NaN
1397,10887,BY78730,Oregon,8879.790017,Yes,Basic,High School or Below,2/3/11,Employed,F,...,0.0,7,Special Auto,Special L2,Offer1,Agent,528.200860,SUV,Small,A
1398,10897,MM70762,Arizona,9075.768214,Yes,Basic,Master,1/26/11,Employed,M,...,0.0,8,Personal Auto,Personal L1,Offer1,Agent,158.077504,Sports Car,Medsize,A

2. Using the original Dataframe, analyze:
   - the average `monthly_premium` and/or customer lifetime value by `policy_type` and `gender` for customers who responded "Yes", and
   - compare these insights to `total_claim_amount` patterns, and discuss which segments appear most profitable or low-risk for the company.

3. Analyze the total number of customers who have policies in each state, and then filter the results to only include states where there are more than 500 customers.

4. Find the maximum, minimum, and median customer lifetime value by education level and gender. Write your conclusions.

In [11]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10910 entries, 0 to 10909
Data columns (total 26 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   unnamed:_0                     10910 non-null  int64
 1   customer                       10910 non-null  str
 2   state                          10279 non-null  str
 3   customer_lifetime_value        10910 non-null  float64
 4   response                       10279 non-null  str
 5   coverage                       10910 non-null  str
 6   education                      10910 non-null  str
 7   effective_to_date              10910 non-null  str
 8   employmentstatus               10910 non-null  str
 9   gender                         10910 non-null  str
 10  income                         10910 non-null  int64
 11  location_code                  10910 non-null  str
 12  marital_status                 10910 non-null  str
 13  monthly_premium_auto           10910 non-null  int64
 14  months_since_last_claim        10277 non-null  float64
 15  months_since_policy_inception  10910 non-null  int64
 16  number_of_open_complaints      10277 non-null  float64
 17  number_of_policies             10910 non-null  int64
 18  policy_type                    10910 non-null  str
 19  policy                         10910 non-null  str
 20  renew_offer_type               10910 non-null  str
 21  sales_channel                  10910 non-null  str
 22  total_claim_amount             10910 non-null  float64
 23  vehicle_class                  10288 non-null  str
 24  vehicle_size                   10288 non-null  str
 25  vehicle_type                   5428 non-null   str
dtypes: float64(4), int64(5), str(17)
memory usage: 3.4 MB

In [12]:
responded_yes_df = df[df["response"] == "Yes"]

In [13]:
analyze_df = responded_yes_df.groupby(["policy_type", "gender"]).agg(
    avg_monthly_premium=("monthly_premium_auto", "mean"),
    avg_clv=("customer_lifetime_value", "mean"),
    avg_claim_amount=("total_claim_amount", "mean"),
    customer_count=("response", "count")
).reset_index()

analyze_df["claim_to_premium_ratio"] = (
    analyze_df["avg_claim_amount"] / analyze_df["avg_monthly_premium"]
)

analyze_df = analyze_df.sort_values(by="avg_clv", ascending=False)

In [14]:
analyze_df

,policy_type,gender,avg_monthly_premium,avg_clv,avg_claim_amount,customer_count,claim_to_premium_ratio
2,Personal Auto,F,98.998148,8339.791842,452.965929,540,4.575499
5,Special Auto,M,86.343750,8247.088702,429.527942,32,4.974627
1,Corporate Auto,M,92.188312,7944.465414,408.582459,154,4.432042
0,Corporate Auto,F,94.301775,7712.628736,433.738499,169,4.599473
4,Special Auto,F,92.314286,7691.584111,453.280164,35,4.910184
3,Personal Auto,M,91.085821,7448.383281,457.010178,536,5.017358

In [15]:
#Most Profitable & Low-Risk Segment - Corporate Auto
#The Core High-Value Segment - Personal Auto (Female)

In [16]:
df_high_volume_states = df.groupby("state").filter(lambda x: len(x) > 500)

In [17]:
df_high_volume_states["state"].value_counts()

state
California    3552
Oregon        2909
Arizona       1937
Nevada         993
Washington     888
Name: count, dtype: int64

In [18]:
clv_summary = df.groupby(["education", "gender"])["customer_lifetime_value"].agg(
    max_clv="max",
    min_clv="min",
    median_clv="median"
).reset_index()

In [19]:
clv_summary

              education gender      max_clv      min_clv   median_clv
0              Bachelor      F  73225.95652  1904.000852  5640.505303
1              Bachelor      M  67907.27050  1898.007675  5548.031892
2               College      F  61850.18803  1898.683686  5623.611187
3               College      M  61134.68307  1918.119700  6005.847375
4                Doctor      F  44856.11397  2395.570000  5332.462694
5                Doctor      M  32677.34284  2267.604038  5577.669457
6  High School or Below      F  55277.44589  2144.921535  6039.553187
7  High School or Below      M  83325.38119  1940.981221  6286.731006
8                Master      F  51016.06704  2417.777032  5729.855012
9                Master      M  50568.25912  2272.307310  5579.099207

In [20]:
#Top Earners (Maximum CLV) - The High School or Below (Male) and Bachelor (Female) segments contain the highest individual customers, reaching peak CLV ceilings of over $83,000 and $73,000 respectively.
#The minimum baseline CLV is stable across all groups, hovering between 1,898 and 2,417, indicating a consistent floor for entry-level or low-value customers regardless of education or gender.
#Median CLVs stay tightly clustered between 5,300 and 6,300 for nearly all segments. This shows that the typical, everyday customer's long-term value remains relatively consistent across different education levels.

## Bonus

5. The marketing team wants to analyze the number of policies sold by state and month. Present the data in a table where the months are arranged as columns and the states are arranged as rows.

6.  Display a new DataFrame that contains the number of policies sold by month, by state, for the top 3 states with the highest number of policies sold.

*Hint:*
- *To accomplish this, you will first need to group the data by state and month, then count the number of policies sold for each group. Afterwards, you will need to sort the data by the count of policies sold in descending order.*
- *Next, you will select the top 3 states with the highest number of policies sold.*
- *Finally, you will create a new DataFrame that contains the number of policies sold by month for each of the top 3 states.*

7. The marketing team wants to analyze the effect of different marketing channels on the customer response rate.

Hint: You can use melt to unpivot the data and create a table that shows the customer response rate (those who responded "Yes") by marketing channel.

External Resources for Data Filtering: https://towardsdatascience.com/filtering-data-frames-in-pandas-b570b1f834b9

In [21]:
print(df.isna().sum())

unnamed:_0                          0
customer                            0
state                             631
customer_lifetime_value             0
response                          631
coverage                            0
education                           0
effective_to_date                   0
employmentstatus                    0
gender                              0
income                              0
location_code                       0
marital_status                      0
monthly_premium_auto                0
months_since_last_claim           633
months_since_policy_inception       0
number_of_open_complaints         633
number_of_policies                  0
policy_type                         0
policy                              0
renew_offer_type                    0
sales_channel                       0
total_claim_amount                  0
vehicle_class                     622
vehicle_size                      622
vehicle_type                     5482
dtype: int64

In [ ]:
df = df.dropna(subset=["months_since_last_claim", "number_of_open_complaints"])

In [58]:
unique_dates = df["effective_to_date"].unique().tolist()

print(unique_dates)

[Timestamp('2011-02-18 00:00:00'), Timestamp('2011-01-18 00:00:00'), Timestamp('2011-02-10 00:00:00'), Timestamp('2011-01-11 00:00:00'), Timestamp('2011-02-14 00:00:00'), Timestamp('2011-02-24 00:00:00'), Timestamp('2011-01-19 00:00:00'), Timestamp('2011-01-04 00:00:00'), Timestamp('2011-01-02 00:00:00'), Timestamp('2011-02-07 00:00:00'), Timestamp('2011-01-31 00:00:00'), Timestamp('2011-01-26 00:00:00'), Timestamp('2011-02-28 00:00:00'), Timestamp('2011-01-16 00:00:00'), Timestamp('2011-01-17 00:00:00'), Timestamp('2011-02-26 00:00:00'), Timestamp('2011-02-23 00:00:00'), Timestamp('2011-01-15 00:00:00'), Timestamp('2011-02-15 00:00:00'), Timestamp('2011-01-24 00:00:00'), Timestamp('2011-02-21 00:00:00'), Timestamp('2011-02-22 00:00:00'), Timestamp('2011-01-07 00:00:00'), Timestamp('2011-01-28 00:00:00'), Timestamp('2011-02-08 00:00:00'), Timestamp('2011-02-12 00:00:00'), Timestamp('2011-02-20 00:00:00'), Timestamp('2011-01-05 00:00:00'), Timestamp('2011-02-19 00:00:00'), Timestamp('2011-01-03 00:00:00'), Timestamp('2011-02-03 00:00:00'), Timestamp('2011-01-22 00:00:00'), Timestamp('2011-01-23 00:00:00'), Timestamp('2011-02-05 00:00:00'), Timestamp('2011-02-13 00:00:00'), Timestamp('2011-01-25 00:00:00'), Timestamp('2011-02-16 00:00:00'), Timestamp('2011-02-01 00:00:00'), Timestamp('2011-01-27 00:00:00'), Timestamp('2011-01-12 00:00:00'), Timestamp('2011-01-20 00:00:00'), Timestamp('2011-02-11 00:00:00'), Timestamp('2011-01-21 00:00:00'), Timestamp('2011-01-29 00:00:00'), Timestamp('2011-02-09 00:00:00'), Timestamp('2011-02-27 00:00:00'), Timestamp('2011-02-17 00:00:00'), Timestamp('2011-02-25 00:00:00'), Timestamp('2011-01-13 00:00:00'), Timestamp('2011-01-06 00:00:00'), Timestamp('2011-02-02 00:00:00'), Timestamp('2011-01-09 00:00:00'), Timestamp('2011-02-04 00:00:00'), Timestamp('2011-01-14 00:00:00'), Timestamp('2011-01-10 00:00:00'), Timestamp('2011-02-06 00:00:00'), Timestamp('2011-01-01 00:00:00'), Timestamp('2011-01-08 00:00:00'), Timestamp('2011-01-30 00:00:00')]

In [23]:
df["effective_to_date"] = pd.to_datetime(df["effective_to_date"], format="mixed")

df["month"] = df["effective_to_date"].dt.strftime("%B")

policy_pivot = pd.pivot_table(
    df,
    index="state",
    columns="month",
    values="response",
    aggfunc="count",
    fill_value=0
)

print(policy_pivot)

month       February  January
state
Arizona          929     1008
California      1634     1918
Nevada           442      551
Oregon          1344     1565
Washington       425      463

In [33]:
state_month_counts = df.groupby(["state", "month"]).size().reset_index(name="policy_count")


top_3_states = (
    state_month_counts.groupby("state")["policy_count"]
    .sum()
    .sort_values(ascending=False)
    .head(3)
    .index.tolist()
)


top_3_df = state_month_counts[state_month_counts["state"].isin(top_3_states)]
top_3_pivot = top_3_df.pivot(
    index="state", 
    columns="month", 
    values="policy_count"
).fillna(0) 

top_3_pivot

month       February  January
state
Arizona          929     1008
California      1634     1918
Oregon          1344     1565

In [26]:
channel_response = (
    df.groupby(["sales_channel", "response"])
    .size()
    .unstack(fill_value=0)
)

In [27]:
channel_rates = channel_response.div(channel_response.sum(axis=1), axis=0) * 100
channel_rates = channel_rates.reset_index()

In [28]:
melted_channels = pd.melt(
    channel_rates,
    id_vars=["sales_channel"],
    value_vars=["Yes", "No"],
    var_name="response_status",
    value_name="percentage"
)

In [29]:
response_rate_yes = (
    melted_channels[melted_channels["response_status"] == "Yes"]
    .rename(columns={"percentage": "response_rate"})
    .sort_values(by="response_rate", ascending=False)
    .reset_index(drop=True)
)

In [30]:
print(response_rate_yes.to_markdown(index=False))

| sales_channel   | response_status   |   response_rate |
|:----------------|:------------------|----------------:|
| Agent           | Yes               |         19.0746 |
| Web             | Yes               |         11.7141 |
| Branch          | Yes               |         11.3787 |
| Call Center     | Yes               |         10.9786 |